#!/usr/bin/env bash
# Install nginx web server port 80
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
/etc/init.d/nginx start
