#!/usr/bin/env bash
# Install nginx web server port 80
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo /etc/init.d/nginx start
