#!/usr/bin/env bash
# Install nginx web server posrt 80
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow http
echo "Holberton School" > /var/www/html/index.html
sudo /etc/init.d/nginx start
