#!/usr/bin/env bash
# displays numbers from 1 to 20
cnt=1
while [ $cnt -le 10 ]
do
	case $cnt in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			echo "Holberton School"
			;;
	esac
	((cnt++))
done
