#!/usr/bin/env bash
# install firewal ufw
sudo apt-get install ufw
# deny all incoming
sudo ufw default deny incoming
# allow all outgoing
sudo ufw default allow outgoing
# allow ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
# restart the ufw
sudo ufw disable
sudo ufw enable
